
[profile.default]
solc = "0.8.25"
evm_version = "cancun"
src = "src"
out = "out"
script = "script"
libs = ["node_modules"]
fs_permissions = [
  { access = "read", path = "out-optimized" },
  { access = "read-write", path = "deployments" },
  { access = "read-write", path = "gas_calculations" },
]
allow_paths = ["*", "/"]

[rpc_endpoints]
odyssey = "https://odyssey.ithaca.xyz/"

[etherscan]
odyssey = { key = "", url = "https://odyssey-explorer.ithaca.xyz/api/" }


[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[fuzz]
runs = 1000
